language: dart

dart:
  - 2.6.0
  - dev

dart_task:
  - test:
  - dartanalyzer: --fatal-infos --fatal-warnings .

matrix:
  include:
  - dart: dev
    dart_task:
      dartfmt: sdk

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
 directories:
   - $HOME/.pub-cache
